swagger: '2.0'
info:
  title: Adobe Experience Platform Data Ingestion
  version: v2
  contact:
      name: Grp-Siphon-Core
basePath: /
host: bulk-ingestion-dev-va7.dev.cloud.adobe.io
tags:
- name: "Ingest Batch"
paths:
  /batches:
    post:
      security:
      - Bearer: []
      tags:
      - "Ingest Batch"
      summary: "Registers a new batch in Adobe Data Catalog"
      description: "Creates a new batch in Data Catalog as a first step to bulk data ingestion. The data is uploaded to this
      batch after which the batch is marked ready for triggering data registration in Catalog"
      operationId: "createBatch"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ingest object that contains information needed to create batch"
        required: true
        schema:
          $ref: "#/definitions/IngestBatch"
      - name: "x-gw-ims-org-id"
        in: "header"
        required: true
        type: "string"
        description: "The id of the ims organization to create the batch under"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Batch"
        400:
          description: "Bad Request. The request is malformed."
        401:
          description: "Unauthorized"
        414:
          description: "URL length exceeds the allowed 2000 characters."
        500:
          description: "Internal server error."
        503:
          description: "Service Unavailable. The bulk ingest api or dependency is unavailable."
  /batches/{batchId}/datasets/{datasetId}/preview:
    get:
      security:
      - Bearer: []
      tags:
      - "Ingest Batch"
      summary: "Generates preview for a batch"
      description: "Generates data preview for the files uploaded to the batch so far. The preview could be generated
      for all the batch datasets collectively or per selected datasets"
      operationId: "getPreview"
      produces:
      - "application/json"
      parameters:
      - name: "batchId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the batch data is being uploaded to"
      - name: "datasetId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the dataset data is being uploaded to"
      - name: "x-gw-ims-org-id"
        in: "header"
        required: true
        type: "string"
        description: "The id of the ims organization associated with the batch"
      - name: "format"
        in: "query"
        required: true
        type: "string"
        description: "The file format for the uploaded file"
      - name: "delimiter"
        in: "query"
        required: false
        type: "string"
        default: ","
        description: "The delimiter to use for parsing column values"
      - name: "quote"
        in: "query"
        required: false
        type: "string"
        default: "\""
        description: "The quote value to use while parsing"
      - name: "escape"
        in: "query"
        required: false
        type: "string"
        default: "\\"
        description: "The escape character to use while parsing"
      - name: "charset"
        in: "query"
        required: false
        type: "string"
        default: "UTF-8"
        description: "The encoding to use for parsing"
      - name: "header"
        in: "query"
        required: false
        type: "boolean"
        default: true
        description: "The flag to indicate if the header is supplied in the dataset files. Currently headerless files
        aren't supported and the header flag should always be true. This is kept for future implementation"
      - name: "nrow"
        in: "query"
        required: false
        type: "integer"
        default: 0
        format: "int32"
        description: "The number of rows to parse"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/PreviewResponse"
        400:
          description: "Bad Request. The request is malformed."
        401:
          description: "Unauthorized. The IMS token provided is invalid."
        404:
          description: "Batch or DataSet resource not found."
        414:
          description: "URL length exceeds the allowed 2000 characters."
        415:
          description: "Unsupported Media Type. The uploaded file media isn't supported."
        500:
          description: "Internal server error."
        503:
          description: "Service Unavailable. The bulk ingest api or dependency is unavailable."
  /batches/{batchId}/datasets/{datasetId}/files:
    post:
      security:
      - Bearer: []
      tags:
      - "Ingest Batch"
      summary: "Upload file to a dataset in a batch"
      description: "For a batch initialized by the bulk ingestion api, this endpoint lets you upload files under
      datasets. You can either upload the entire file in a single multipart request or upload the file in patches/parts
      using the resumable upload option. We have soft size limits enforced by the gateways which is why a file larger than
      512MB can only be uploaded via the resumable option.\n To choose the resumable upload, you need to specify the query
      param uploadType=resumable and then use the file PATCH endpoint below to send the subsequent byte ranges"
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "batchId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the batch data is being uploaded to"
      - name: "datasetId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the dataset data is being uploaded to"
      - name: "x-gw-ims-org-id"
        in: "header"
        required: true
        type: "string"
        description: "The id of the ims organization associated with the batch"
      - name: "uploadType"
        in: "query"
        required: true
        type: "string"
        enum: ["resumable"]
        description: "The optional uploadType with the only supported value being 'resumable'. By default, the files
        are uploaded in a single multipart request but if the file is larger than 512MB, it needs to be sent in parts
        or 512MB or lesser as multiple requests"
      - in: "formData"
        name: "file"
        type: "file"
        required: true
        description: The content bytes for the file or file part being uploaded
      responses:
        201:
          description: "Created"
          headers:
            Location:
              type: "string"
              description: "/batches/{batchId}/datasets/{datasetId}/files/{fileId}"
          schema:
            $ref: "#/definitions/File"
        400:
          description: "Bad Request. The request is malformed."
        401:
          description: "Unauthorized. The IMS token provided is invalid."
        404:
          description: "Batch or DataSet resource not found."
        414:
          description: "URL length exceeds the allowed 2000 characters."
        415:
          description: "Unsupported Media Type. The uploaded file media isn't supported."
        500:
          description: "Internal server error."
        503:
          description: "Service Unavailable. The bulk ingest api or dependency is unavailable."
  /batches/{batchId}/datasets/{datasetId}/files/{fileId}:
    patch:
      security:
      - Bearer: []
      tags:
      - "Ingest Batch"
      summary: "Upload file part to a resumable file being uploaded to a batch dataset"
      description: "Files larger than 512MB are uploaded in parts and this PATCH endpoint provides you a way
      to upload a part of your large file that was initialized via the POST endpoint above"
      operationId: "uploadFilePart"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "batchId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the batch data is being uploaded to"
      - name: "datasetId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the dataset data is being uploaded to"
      - name: "fileId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the file the file part is being uploaded for"
      - name: "x-gw-ims-org-id"
        in: "header"
        required: true
        type: "string"
        description: "The id of the ims organization associated with the batch"
      - name: "Content-Range"
        in: "header"
        required: true
        type: "string"
        description: "The range of bytes of the file being uploaded with this request"
      - in: "formData"
        name: "file"
        type: "file"
        required: true
        description: The content bytes for the file or file part being uploaded
      responses:
        200:
          description: "successful operation"
          headers:
            Range:
              type: "string"
              description: "bytes 0-512000000"
          schema:
            $ref: "#/definitions/File"
        400:
          description: "Bad Request. The request is malformed."
        401:
          description: "Unauthorized. The IMS token provided is invalid."
        404:
          description: "Batch or DataSet or File resource not found."
        414:
          description: "URL length exceeds the allowed 2000 characters."
        415:
          description: "Unsupported Media Type. The uploaded file media isn't supported."
        500:
          description: "Internal server error."
        503:
          description: "Service Unavailable. The bulk ingest api or dependency is unavailable."
    post:
      security:
      - Bearer: []
      tags:
      - "Ingest Batch"
      summary: "Operate on the identified file"
      description: "Used to signal completion of the file that's uploaded in parts"
      operationId: "completeFileUpload"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "batchId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the batch data is being uploaded to"
      - name: "datasetId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the dataset data is being uploaded to"
      - name: "fileId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the file the file part is being uploaded for"
      - name: "x-gw-ims-org-id"
        in: "header"
        required: true
        type: "string"
        description: "The id of the ims organization associated with the batch"
      - name: "action"
        in: "query"
        required: true
        type: "string"
        description: "The action to perform on the file with the only supported value currently being COMPLETE"
        enum: ["COMPLETE"]
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/File"
        400:
          description: "Bad Request. The request is malformed."
        401:
          description: "Unauthorized. The IMS token provided is invalid."
        404:
          description: "Batch or DataSet or File resource not found."
        414:
          description: "URL length exceeds the allowed 2000 characters."
        500:
          description: "Internal server error."
        503:
          description: "Service Unavailable. The bulk ingest api or dependency is unavailable."
  /batches/{batchId}:
    post:
      security:
      - Bearer: []
      tags:
      - "Ingest Batch"
      summary: "Promote batch"
      description: "Update the batch to trigger the downstream data promotion workflow"
      operationId: "promoteBatch"
      produces:
      - "application/json"
      parameters:
      - name: "batchId"
        in: "path"
        required: true
        type: "string"
        description: "The id of the batch that needs to be updated"
      - name: "x-gw-ims-org-id"
        in: "header"
        required: true
        type: "string"
        description: "The id of the ims organization associated with the batch"
      - name: "action"
        in: "query"
        required: true
        type: "string"
        description: "The action to take on the Batch"
        enum: ["COMPLETE", "ABORT","FAIL", "REVERT"]
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Batch"
        400:
          description: "Bad Request. The request is malformed."
        401:
          description: "Unauthorized. The IMS token provided is invalid."
        404:
          description: "Batch not found."
        414:
          description: "URL length exceeds the allowed 2000 characters."
        500:
          description: "Internal server error."
        503:
          description: "Service Unavailable. The bulk ingest api or dependency is unavailable."
definitions:
  File:
    type: "object"
    properties:
      name:
        type: "string"
      sizeInBytes:
        type: "integer"
        format: "int64"
  Column:
    type: "object"
    properties:
      cid:
        type: "string"
      name:
        type: "string"
  FormatParams:
    type: "object"
    properties:
      delimiter:
        type: "string"
      quote:
        type: "string"
      escape:
        type: "string"
      charset:
        type: "string"
      header:
        type: "boolean"
      format:
        type: "string"
  Preview:
    type: "object"
    properties:
      columns:
        type: "array"
        items:
          $ref: "#/definitions/Column"
      rows:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            type: "string"
  PreviewResponse:
    type: "object"
    properties:
      formatParams:
        $ref: "#/definitions/FormatParams"
      preview:
        $ref: "#/definitions/Preview"
  Batch:
    type: object
    properties:
      id:
        type: string
        description: The batch identifier.
      imsOrg:
        type: string
        description: The owning IMS organization identifier.
      created:
        type: integer
        description: The Unix timestamp (in milliseconds) when this Batch was persisted.
        readOnly: true
      createdClient:
        type: string
        description: The ID of the IMS client that created this Batch.
        readOnly: true
      createdUser:
        type: string
        description: The ID of the user who created this object.
        readOnly: true
      updatedUser:
        type: string
        description: The ID of the user who changed this object.
        readOnly: true
      updated:
        type: integer
        description: The Unix timestamp (in milliseconds) of last modification.
        readOnly: true
      started:
        type: integer
        description: >-
          The Unix timestamp (in milliseconds) when the Batch processing action
          was started.
      completed:
        type: integer
        description: >-
          The Unix timestamp (in milliseconds) when the Batch processing action
          was completed. Completed - Started should yield the total processing
          time.
      status:
        type: string
        description: The current (mutable) status of this Batch.
        enum:
          - processing
          - success
          - failure
          - queued
          - retrying
          - stalled
      recordCount:
        type: integer
        description: >-
          The total number of data records (rows/documents) processed in this
          Batch.
      failedRecordCount:
        type: integer
        description: The number of records that could not be processed in this Batch.
      errors:
        type: array
        description: ''
        items:
          $ref: '#/definitions/errors'
      size:
        type: integer
        description: Number of bytes processed in this Batch.
      version:
        type: string
        description: The Semantic version of the Batch. Updated when the Batch is modified.
        readOnly: true
      availableDates:
        type: object
        description: >-
          Describes what date range of data is available in the Batch. Null if
          dates aren't relevant for data related to this Batch.
        properties:
          startDate:
            type: integer
            description: >-
              The Unix timestamp (in seconds) for the most recent data available
              in this Batch.
          endDate:
            type: integer
            description: >-
              The Unix timestamp (in seconds) for the oldest data available in
              this Batch.
      relatedObjects:
        type: array
        description: A list of the objects involved with this Batch.
        items:
          $ref: '#/definitions/relatedObjects'
      metrics:
        type: object
        description: >-
          Contains metrics related to this Batch.  Metric names are determined
          by the producer of the object since each Batch may want to record
          metrics that are relevant to the process
        properties: {}
      tags:
        type: object
        description: >-
          Tags are values associated with a particular object,  these are
          generally used by external systems for marking an object in a way that
          it understands.  Normally tags are not used for internal Catalog
          business logic
        properties: {}
    required:
      - imsOrg
      - status
  errors:
    type: object
    properties:
      code:
        type: string
        description: >-
          An enumerated code that details the type of error encountered. This
          value should be understandable by the reader and writer and eventually
          allow for localized error message (and solution) descriptions.
      rows:
        type: array
        description: >-
          Indicates which rows exhibit this error. Could be a single number, or
          a hyphen-delimited range.
        items:
          type: string
          description: Row or range of rows this error was encountered on.
      description:
        type: string
        description: >-
          A human-readable description of the error. This message may be
          transmitted to clients, but isn't meant for customer-facing UIS.
  relatedObjects:
    type: object
    properties:
      type:
        type: string
        description: The type of object processed in this Batch.
        enum:
          - batch
          - connection
          - connector
          - dataSet
          - dataSetFile
          - dataSetView
          - transform
      id:
        type: string
        description: ''
      tag:
        type: string
        description: >-
          The name for the relation the specified object had with this Batch
          operation. Examples: input, output, trigger, etc.
      status:
        type: string
        description: The current (mutable) status of this dataset.
        enum:
          - processing
          - success
          - failure
          - queued
          - retrying
          - stalled
      errors:
        type: array
        description: ''
        items:
          $ref: '#/definitions/errors'
      metrics:
        type: object
        description: Contains metrics related to this dataset.
        additionalProperties:
          type: integer
  IngestBatch:
    type: "object"
    properties:
      datasetId:
        type: "string"
